services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nhpc_user
      POSTGRES_PASSWORD: nhpc_pass
      POSTGRES_DB: nhpc_blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: