import type { Metadata } from "next";
import "@/app/globals.css";
import { NavbarDemo } from "./component/nav";
import Footer from "./component/footer";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "NHPC Ltd. | Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="min-h-screen grid grid-rows-[auto_1fr_auto] gap-4 ">
          <SessionProvider><NavbarDemo/></SessionProvider>
          <main className="min-h-fit overflow-scroll ">{children}</main>
          <Footer/>
        </div>
  );
}
