import type { Metadata } from "next";
import "@/app/globals.css";
import { NavbarDemo } from "./component/nav";
import Footer from "./component/footer";

export const metadata: Metadata = {
  title: "NHPC Ltd. | Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <div className="min-h-screen grid grid-rows-[auto_1fr_auto] gap-4">
            <NavbarDemo />
            <main className="min-h-fit overflow-hidden">{children}</main>
            <Footer />
          </div>
      </body>
    </html>
  );
}