import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { NavbarDemo } from "../(root)/component/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NHPC Ltd. | Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NavbarDemo/> */}
        <main className="h-screen flex flex-col justify-center items-center">
        <div className="bg-slate-100 p-10 rounded-md">{children}</div>
        </main>
      </body>
    </html>
  );
}
